@baseUrl = http://localhost:8000/

# @name loginResponse
post {{baseUrl}}auth/login
Content-Type: application/json

{
  "email": "lequochung19971@gmail.com",
  "password": "Lequochung@12"
}


### 

# @name refreshTokenResponse
post {{baseUrl}}auth/refreshToken
Content-Type: application/json

###
get {{baseUrl}}products
Content-Type: application/json

###
get {{baseUrl}}auth/me
Content-Type: application/json